name = "BasicMesh"
uuid = "5ba12469-52ae-495e-a2c1-ff3b69a1384d"
authors = ["LukasOstien <lukas.ostien@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
